volumes:
  minio_storage: {}

services:
  traefik:
    image: traefik:v3.1
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik-network

  frontend:
    build:
      context: front
      dockerfile: Dockerfile
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.service=frontend
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.services.frontend.loadbalancer.server.port=80

  # minio:
  #   image: minio/minio
  #   volumes:
  #     - minio_storage:/data
  #   expose:
  #     - 9000
  #     - 9001
  #   ports:
  #     - 9001:9001
  #   environment:
  #     MINIO_ROOT_USER: masoud
  #     MINIO_ROOT_PASSWORD: Strong#Pass#2022
  #   command: server --console-address ":9001" /data
  #   labels:
  #     - traefik.enable=true

  #     - traefik.http.routers.minio.entrypoints=web
  #     - traefik.http.routers.minio.service=minio
  #     - traefik.http.routers.minio.rule=PathPrefix(`/s3`)
  #     - "traefik.http.routers.minio.middlewares=strip-s3"
  #     - "traefik.http.middlewares.strip-s3.stripprefix.prefixes=/s3"
  #     - traefik.http.services.minio.loadbalancer.server.port=9000

  #     - traefik.http.routers.minioconsole.entrypoints=web
  #     - traefik.http.routers.minioconsole.service=minioconsole
  #     - traefik.http.routers.minioconsole.rule=PathPrefix(`/s3console`)
  #     - traefik.http.routers.minioconsole.middlewares=strip-s3console
  #     - traefik.http.middlewares.strip-s3console.stripprefix.prefixes=/s3console
  #     - traefik.http.services.minioconsole.loadbalancer.server.port=9001

  #   networks:
  #     - traefik-network

networks:
  traefik-network:
    driver: bridge
