FROM python:3.12

EXPOSE 8000

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ./src ./src


CMD ["fastapi", "dev", "src/main.py",  "--port", "8000", "--host", "0.0.0.0", "--proxy-headers"]